name: Deploy Laravel Backend

# Trigger the workflow on push and pull request events on the production branch
on:
    push:
      branches:
        - main
      paths-ignore:
        - 'react/**'
    pull_request:
      branches:
        - main
      paths-ignore:
        - 'react/**' 

# Authenticate to the the server via ssh and run our deployment script 
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
  
        - name: Checkout Repository
          uses: actions/checkout@v2
  
        - name: Directory Permissions
          run: chmod -R 777 storage bootstrap/cache
  
        - name: SSH into Server and Deploy
          if: ${{ success() }}
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            password: ${{ secrets.SSH_PRIVATE_PASSWORD }}
            port: ${{ secrets.SERVER_PORT }}
            script: |
                cd ${{ secrets.PROJECT_PATH }}
                git pull origin main
                git clean -f -d
                php artisan migrate --force
                php artisan cache:clear
                php artisan config:cache
